CREATE TABLE TASK_GROUP (
	ID BIGINT AUTO_INCREMENT PRIMARY KEY, 
	NAME TEXT NOT NULL,
	UUID VARCHAR(64) NOT NULL,
	CREATED TIMESTAMP NOT NULL
);


CREATE INDEX TASK_GROUP_UUID_IDX ON TASK_GROUP (UUID);

CREATE INDEX TASK_GROUP_CREATED_IDX ON TASK_GROUP (CREATED);


CREATE TABLE TASK (
	ID BIGINT AUTO_INCREMENT PRIMARY KEY, 
	NAME TEXT,
	UUID VARCHAR(64) NOT NULL,
	CREATED TIMESTAMP NOT NULL,
	STATUS VARCHAR(32) NOT NULL,
	PRIORITY INTEGER NOT NULL,
	TASK_GROUP_ID BIGINT NOT NULL
);

CREATE INDEX TASK_UUID_IDX ON TASK (UUID);

CREATE INDEX TASK_CREATED_IDX ON TASK (CREATED);

CREATE INDEX TASK_TASK_GROUP_ID_IDX ON TASK (TASK_GROUP_ID);

ALTER TABLE TASK ADD FOREIGN KEY(TASK_GROUP_ID) REFERENCES TASK_GROUP(ID) ON DELETE CASCADE;
